# Generated by Django 4.0.6 on 2022-07-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_url',
            field=models.TextField(verbose_name='Product URL'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_url_image',
            field=models.TextField(verbose_name='Product Image URL'),
        ),
    ]
