# Generated by Django 4.0.6 on 2022-07-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_product_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='consult_date',
            field=models.DateField(verbose_name='Consultation Date'),
        ),
    ]
